/* Generated by re2c 2.2 on Sat Oct 30 11:21:34 2021 */
#line 1 "../src/parse/lex_conf.re"
#include "src/util/c99_stdint.h"
#include <string>

#include "src/encoding/enc.h"
#include "src/msg/msg.h"
#include "src/options/opt.h"
#include "src/parse/ast.h"
#include "src/parse/scanner.h"
#include "src/util/file_utils.h"
#include "src/util/s_to_n32_unsafe.h"
#include "src/util/string_utils.h"


namespace re2c {

#define YYFILL(n) do { if (!fill(n)) { error("unexpected end of input"); exit(1); }} while(0)

// global re2c config (affects the whole file)
#line 39 "../src/parse/lex_conf.re"


void Scanner::lex_conf(Opt &opts)
{
    tok = cur;

#line 29 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,  32,   0,   0, 
		160, 160, 160, 160, 160, 160, 160, 160, 
		160, 160,  32,   0,   0,   0,   0,   0, 
		  0,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,   0,   0,   0,   0,  32, 
		  0,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((lim - cur) < 28) YYFILL(28);
	yych = (unsigned char)*cur;
	switch (yych) {
	case '-':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'b':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 'u':
	case 'w':
	case 'x':
	case 'z':	goto yy3;
	case 'a':	goto yy5;
	case 'c':	goto yy6;
	case 'd':	goto yy7;
	case 'e':	goto yy8;
	case 'f':	goto yy9;
	case 'i':	goto yy10;
	case 'l':	goto yy11;
	case 's':	goto yy12;
	case 't':	goto yy13;
	case 'v':	goto yy14;
	case 'y':	goto yy15;
	default:	goto yy2;
	}
yy2:
#line 192 "../src/parse/lex_conf.re"
	{
        msg.error(tok_loc(), "unrecognized configuration '%.*s'",
            static_cast<int>(cur - tok), tok);
        exit(1);
    }
#line 144 "src/parse/lex_conf.cc"
yy3:
	++cur;
	if (lim <= cur) YYFILL(1);
	yych = (unsigned char)*cur;
yy4:
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	goto yy2;
yy5:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy16;
	goto yy4;
yy6:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy17;
	if (yych == 'o') goto yy18;
	goto yy4;
yy7:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy19;
	goto yy4;
yy8:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy20;
	goto yy4;
yy9:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy21;
	goto yy4;
yy10:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy22;
	goto yy4;
yy11:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy23;
	goto yy4;
yy12:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy24;
	if (yych == 't') goto yy25;
	goto yy4;
yy13:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy26;
	goto yy4;
yy14:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy27;
	goto yy4;
yy15:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy28;
	goto yy4;
yy16:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy29;
	goto yy4;
yy17:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy30;
	goto yy4;
yy18:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy31;
	goto yy4;
yy19:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy32;
	goto yy4;
yy20:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy33;
	goto yy4;
yy21:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy35;
	goto yy4;
yy22:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy36;
	goto yy4;
yy23:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy37;
	goto yy4;
yy24:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy38;
	goto yy4;
yy25:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy39;
	goto yy4;
yy26:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy40;
	goto yy4;
yy27:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy41;
	goto yy4;
yy28:
	yych = (unsigned char)*++cur;
	if (yych <= 'c') {
		if (yych <= 'a') goto yy4;
		if (yych <= 'b') goto yy42;
		goto yy43;
	} else {
		if (yych == 'f') goto yy44;
		goto yy4;
	}
yy29:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy45;
	goto yy4;
yy30:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy46;
	goto yy4;
yy31:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy47;
	goto yy4;
yy32:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy48;
	goto yy4;
yy33:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 81 "../src/parse/lex_conf.re"
	{ opts.set_eof     (lex_conf_eof()); return; }
#line 281 "src/parse/lex_conf.cc"
yy35:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy49;
	goto yy4;
yy36:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy50;
	goto yy4;
yy37:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy51;
	goto yy4;
yy38:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy52;
	goto yy4;
yy39:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy53;
	if (yych == 't') goto yy54;
	goto yy4;
yy40:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy55;
	goto yy4;
yy41:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy56;
	goto yy4;
yy42:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy57;
	goto yy4;
yy43:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy58;
	goto yy4;
yy44:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy59;
	goto yy4;
yy45:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy60;
	goto yy4;
yy46:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy61;
	goto yy4;
yy47:
	yych = (unsigned char)*++cur;
	if (yych <= 'd') {
		if (yych == ':') goto yy62;
		goto yy4;
	} else {
		if (yych <= 'e') goto yy63;
		if (yych == 'p') goto yy64;
		goto yy4;
	}
yy48:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy65;
	goto yy4;
yy49:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy66;
	goto yy4;
yy50:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy67;
	goto yy4;
yy51:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy68;
	goto yy4;
yy52:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy69;
	goto yy4;
yy53:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy70;
	goto yy4;
yy54:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy71;
	goto yy4;
yy55:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy72;
	goto yy4;
yy56:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy73;
	goto yy4;
yy57:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy74;
	goto yy4;
yy58:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy75;
	goto yy4;
yy59:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy76;
	goto yy4;
yy60:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy77;
	if (yych == 't') goto yy78;
	goto yy4;
yy61:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy79;
	goto yy4;
yy62:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy80;
	if (yych == 'g') goto yy81;
	goto yy4;
yy63:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy82;
	goto yy4;
yy64:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy83;
	goto yy4;
yy65:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy84;
	goto yy4;
yy66:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy85;
	goto yy4;
yy67:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy86;
	goto yy4;
yy68:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy87;
	if (yych == 'p') goto yy88;
	goto yy4;
yy69:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy89;
	goto yy4;
yy70:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy90;
	goto yy4;
yy71:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy91;
	goto yy4;
yy72:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy92;
	if (yych == 'p') goto yy93;
	goto yy4;
yy73:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy94;
	goto yy4;
yy74:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy95;
	goto yy4;
yy75:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy96;
	if (yych == 'e') goto yy97;
	goto yy4;
yy76:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy98;
	goto yy4;
yy77:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy99;
	goto yy4;
yy78:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy100;
	goto yy4;
yy79:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy101;
	goto yy4;
yy80:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy102;
	goto yy4;
yy81:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy103;
	goto yy4;
yy82:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy104;
	goto yy4;
yy83:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy105;
	goto yy4;
yy84:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy106;
	goto yy4;
yy85:
	yych = (unsigned char)*++cur;
	switch (yych) {
	case '8':	goto yy107;
	case 'P':	goto yy109;
	case 'T':	goto yy111;
	case 'b':	goto yy113;
	case 'c':	goto yy115;
	case 'd':	goto yy116;
	case 'e':	goto yy118;
	case 'g':	goto yy120;
	case 'i':	goto yy122;
	case 'l':	goto yy124;
	case 'n':	goto yy125;
	case 'p':	goto yy126;
	case 's':	goto yy127;
	case 't':	goto yy129;
	case 'u':	goto yy131;
	case 'w':	goto yy133;
	case 'x':	goto yy135;
	default:	goto yy4;
	}
yy86:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy137;
	goto yy4;
yy87:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy138;
	goto yy4;
yy88:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy139;
	goto yy4;
yy89:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy140;
	goto yy4;
yy90:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy141;
	goto yy4;
yy91:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy142;
	if (yych == 'n') goto yy143;
	goto yy4;
yy92:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy144;
	goto yy4;
yy93:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy145;
	goto yy4;
yy94:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy146;
	goto yy4;
yy95:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy147;
	goto yy4;
yy96:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy148;
	goto yy4;
yy97:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy149;
	goto yy4;
yy98:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy150;
	goto yy4;
yy99:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy151;
	goto yy4;
yy100:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy152;
	goto yy4;
yy101:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy153;
	goto yy4;
yy102:
	yych = (unsigned char)*++cur;
	if (yych == 'v') goto yy154;
	goto yy4;
yy103:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy155;
	goto yy4;
yy104:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy156;
	goto yy4;
yy105:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy157;
	goto yy4;
yy106:
	yych = (unsigned char)*++cur;
	if (yych == 'Y') goto yy158;
	goto yy4;
yy107:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 75 "../src/parse/lex_conf.re"
	{ lex_conf_enc(Enc::UTF8, opts);   return; }
#line 608 "src/parse/lex_conf.cc"
yy109:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 64 "../src/parse/lex_conf.re"
	{
        bool b = lex_conf_bool();
        opts.set_posix_syntax(b);
        opts.set_posix_semantics(b);
        return;
    }
#line 621 "src/parse/lex_conf.cc"
yy111:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 49 "../src/parse/lex_conf.re"
	{ opts.set_tags             (lex_conf_bool());   return; }
#line 629 "src/parse/lex_conf.cc"
yy113:
	yych = (unsigned char)*++cur;
	if (yych <= 'Z') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= ':') goto yy3;
			if (yych >= 'A') goto yy3;
		}
	} else {
		if (yych <= '`') {
			if (yych == '_') goto yy3;
		} else {
			if (yych == 'i') goto yy159;
			if (yych <= 'z') goto yy3;
		}
	}
yy114:
#line 45 "../src/parse/lex_conf.re"
	{ opts.set_bFlag            (lex_conf_bool());   return; }
#line 650 "src/parse/lex_conf.cc"
yy115:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy160;
	if (yych == 'o') goto yy161;
	goto yy4;
yy116:
	yych = (unsigned char)*++cur;
	if (yych <= 'Z') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= ':') goto yy3;
			if (yych >= 'A') goto yy3;
		}
	} else {
		if (yych <= '`') {
			if (yych == '_') goto yy3;
		} else {
			if (yych == 'e') goto yy162;
			if (yych <= 'z') goto yy3;
		}
	}
yy117:
#line 46 "../src/parse/lex_conf.re"
	{ opts.set_dFlag            (lex_conf_bool());   return; }
#line 676 "src/parse/lex_conf.cc"
yy118:
	yych = (unsigned char)*++cur;
	if (yych <= '_') {
		if (yych <= ':') {
			if (yych == '-') goto yy3;
			if (yych >= '0') goto yy3;
		} else {
			if (yych <= '@') goto yy119;
			if (yych <= 'Z') goto yy3;
			if (yych >= '_') goto yy3;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= '`') goto yy119;
			if (yych == 'c') goto yy163;
			goto yy3;
		} else {
			if (yych <= 'm') goto yy164;
			if (yych <= 'n') goto yy165;
			if (yych <= 'z') goto yy3;
		}
	}
yy119:
#line 71 "../src/parse/lex_conf.re"
	{ lex_conf_enc(Enc::EBCDIC, opts); return; }
#line 702 "src/parse/lex_conf.cc"
yy120:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 47 "../src/parse/lex_conf.re"
	{ opts.set_gFlag            (lex_conf_bool());   return; }
#line 710 "src/parse/lex_conf.cc"
yy122:
	yych = (unsigned char)*++cur;
	if (yych <= 'Z') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= ':') goto yy3;
			if (yych >= 'A') goto yy3;
		}
	} else {
		if (yych <= '`') {
			if (yych == '_') goto yy3;
		} else {
			if (yych == 'n') goto yy166;
			if (yych <= 'z') goto yy3;
		}
	}
yy123:
#line 186 "../src/parse/lex_conf.re"
	{
        msg.error(tok_loc(), "configurations `flags:i`, `flags:no-debug-info` "
            "are deprecated, use global options `-i`, `--no-debug-info` instead");
        exit(1);
    }
#line 735 "src/parse/lex_conf.cc"
yy124:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy167;
	goto yy4;
yy125:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy168;
	if (yych == 'o') goto yy169;
	goto yy4;
yy126:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy170;
	goto yy4;
yy127:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 48 "../src/parse/lex_conf.re"
	{ opts.set_sFlag            (lex_conf_bool());   return; }
#line 756 "src/parse/lex_conf.cc"
yy129:
	yych = (unsigned char)*++cur;
	if (yych <= '^') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= ':') goto yy3;
			if (yych <= '@') goto yy130;
			if (yych <= 'Z') goto yy3;
		}
	} else {
		if (yych <= 'a') {
			if (yych <= '_') goto yy3;
			if (yych >= 'a') goto yy171;
		} else {
			if (yych == 'y') goto yy172;
			if (yych <= 'z') goto yy3;
		}
	}
yy130:
#line 56 "../src/parse/lex_conf.re"
	{
        std::string name(lex_conf_string());
        std::string path(opts.glob.output_file);
        get_dir(path);
        opts.set_header_file(path + name);
        return;
    }
#line 785 "src/parse/lex_conf.cc"
yy131:
	yych = (unsigned char)*++cur;
	if (yych <= '^') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= ':') goto yy3;
			if (yych <= '@') goto yy132;
			if (yych <= 'Z') goto yy3;
		}
	} else {
		if (yych <= 'n') {
			if (yych == '`') goto yy132;
			if (yych <= 'm') goto yy3;
			goto yy173;
		} else {
			if (yych == 't') goto yy174;
			if (yych <= 'z') goto yy3;
		}
	}
yy132:
#line 72 "../src/parse/lex_conf.re"
	{ lex_conf_enc(Enc::UTF32, opts);  return; }
#line 809 "src/parse/lex_conf.cc"
yy133:
	yych = (unsigned char)*++cur;
	if (yych <= 'Z') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= ':') goto yy3;
			if (yych >= 'A') goto yy3;
		}
	} else {
		if (yych <= '`') {
			if (yych == '_') goto yy3;
		} else {
			if (yych == 'i') goto yy175;
			if (yych <= 'z') goto yy3;
		}
	}
yy134:
#line 73 "../src/parse/lex_conf.re"
	{ lex_conf_enc(Enc::UCS2, opts);   return; }
#line 830 "src/parse/lex_conf.cc"
yy135:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 74 "../src/parse/lex_conf.re"
	{ lex_conf_enc(Enc::UTF16, opts);  return; }
#line 838 "src/parse/lex_conf.cc"
yy137:
	yych = (unsigned char)*++cur;
	if (yych <= 'r') goto yy4;
	if (yych <= 's') goto yy176;
	if (yych <= 't') goto yy177;
	goto yy4;
yy138:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy178;
	goto yy4;
yy139:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy179;
	goto yy4;
yy140:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy180;
	goto yy4;
yy141:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy182;
	goto yy4;
yy142:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy183;
	goto yy4;
yy143:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy184;
	goto yy4;
yy144:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy185;
	goto yy4;
yy145:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy186;
	goto yy4;
yy146:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy187;
	goto yy4;
yy147:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy188;
	goto yy4;
yy148:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy190;
	goto yy4;
yy149:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy191;
	goto yy4;
yy150:
	yych = (unsigned char)*++cur;
	if (yych <= 'd') {
		if (yych == 'c') goto yy192;
		goto yy4;
	} else {
		if (yych <= 'e') goto yy193;
		if (yych == 'p') goto yy194;
		goto yy4;
	}
yy151:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy195;
	goto yy4;
yy152:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy197;
	goto yy4;
yy153:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy199;
	goto yy4;
yy154:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy200;
	goto yy4;
yy155:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy201;
	goto yy4;
yy156:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy203;
	goto yy4;
yy157:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy204;
	goto yy4;
yy158:
	yych = (unsigned char)*++cur;
	if (yych == 'Y') goto yy205;
	goto yy4;
yy159:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy206;
	goto yy4;
yy160:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy207;
	goto yy4;
yy161:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy208;
	goto yy4;
yy162:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy209;
	goto yy4;
yy163:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy210;
	goto yy4;
yy164:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy211;
	goto yy4;
yy165:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy212;
	goto yy4;
yy166:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy213;
	goto yy4;
yy167:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy214;
	goto yy4;
yy168:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy215;
	goto yy4;
yy169:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy216;
	goto yy4;
yy170:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy217;
	goto yy4;
yy171:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy218;
	goto yy4;
yy172:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy219;
	goto yy4;
yy173:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy220;
	goto yy4;
yy174:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy221;
	goto yy4;
yy175:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy222;
	goto yy4;
yy176:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy223;
	goto yy4;
yy177:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy224;
	goto yy4;
yy178:
	yych = (unsigned char)*++cur;
	if (yych == 'F') goto yy225;
	if (yych == 'N') goto yy226;
	goto yy4;
yy179:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy227;
	goto yy4;
yy180:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 82 "../src/parse/lex_conf.re"
	{ opts.set_sentinel(lex_conf_eof()); return; }
#line 1027 "src/parse/lex_conf.cc"
yy182:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy228;
	goto yy4;
yy183:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy229;
	goto yy4;
yy184:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy230;
	goto yy4;
yy185:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy231;
	goto yy4;
yy186:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy232;
	goto yy4;
yy187:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy233;
	goto yy4;
yy188:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 112 "../src/parse/lex_conf.re"
	{ opts.set_yybmHexTable (lex_conf_bool()); return; }
#line 1059 "src/parse/lex_conf.cc"
yy190:
	yych = (unsigned char)*++cur;
	if (yych == 'v') goto yy234;
	goto yy4;
yy191:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy235;
	goto yy4;
yy192:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy237;
	goto yy4;
yy193:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy238;
	goto yy4;
yy194:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy239;
	goto yy4;
yy195:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 146 "../src/parse/lex_conf.re"
	{ opts.set_api_sigil(lex_conf_string()); return; }
#line 1087 "src/parse/lex_conf.cc"
yy197:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 145 "../src/parse/lex_conf.re"
	{ lex_conf_api_style(opts); return; }
#line 1095 "src/parse/lex_conf.cc"
yy199:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy240;
	goto yy4;
yy200:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy241;
	goto yy4;
yy201:
	yyaccept = 0;
	yych = (unsigned char)*(mar = ++cur);
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	if (yych == '@') goto yy242;
yy202:
#line 96 "../src/parse/lex_conf.re"
	{ opts.set_condGoto         (lex_conf_string ()); return; }
#line 1114 "src/parse/lex_conf.cc"
yy203:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy244;
	goto yy4;
yy204:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy245;
	goto yy4;
yy205:
	yych = (unsigned char)*++cur;
	switch (yych) {
	case 'B':	goto yy247;
	case 'C':	goto yy248;
	case 'D':	goto yy249;
	case 'F':	goto yy250;
	case 'G':	goto yy251;
	case 'L':	goto yy252;
	case 'M':	goto yy253;
	case 'P':	goto yy254;
	case 'R':	goto yy255;
	case 'S':	goto yy256;
	default:	goto yy4;
	}
yy206:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy257;
	goto yy4;
yy207:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy258;
	goto yy4;
yy208:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy259;
	goto yy4;
yy209:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy260;
	goto yy4;
yy210:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	goto yy119;
yy211:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy261;
	goto yy4;
yy212:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy262;
	goto yy4;
yy213:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy263;
	goto yy4;
yy214:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy264;
	goto yy4;
yy215:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy265;
	goto yy4;
yy216:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy266;
	goto yy4;
yy217:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy267;
	goto yy4;
yy218:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy111;
	goto yy4;
yy219:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy268;
	goto yy4;
yy220:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy269;
	goto yy4;
yy221:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy270;
	goto yy4;
yy222:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy271;
	goto yy4;
yy223:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy272;
	goto yy4;
yy224:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy273;
	goto yy4;
yy225:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy275;
	goto yy4;
yy226:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy276;
	goto yy4;
yy227:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy277;
	goto yy4;
yy228:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy278;
	goto yy4;
yy229:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy280;
	goto yy4;
yy230:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy281;
	goto yy4;
yy231:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy282;
	goto yy4;
yy232:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy283;
	goto yy4;
yy233:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy284;
	goto yy4;
yy234:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy285;
	goto yy4;
yy235:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 167 "../src/parse/lex_conf.re"
	{ opts.set_bEmitYYCh      (lex_conf_bool()); return; }
#line 1263 "src/parse/lex_conf.cc"
yy237:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy286;
	goto yy4;
yy238:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy287;
	goto yy4;
yy239:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy288;
	goto yy4;
yy240:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy289;
	goto yy4;
yy241:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy290;
	goto yy4;
yy242:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy291;
yy243:
	cur = mar;
	if (yyaccept <= 2) {
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto yy202;
			} else {
				goto yy279;
			}
		} else {
			goto yy348;
		}
	} else {
		if (yyaccept <= 4) {
			if (yyaccept == 3) {
				goto yy415;
			} else {
				goto yy620;
			}
		} else {
			goto yy700;
		}
	}
yy244:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy292;
	goto yy4;
yy245:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 92 "../src/parse/lex_conf.re"
	{ opts.set_condPrefix       (lex_conf_string ()); return; }
#line 1321 "src/parse/lex_conf.cc"
yy247:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy293;
	goto yy4;
yy248:
	yych = (unsigned char)*++cur;
	if (yych <= 'S') {
		if (yych == 'O') goto yy294;
		goto yy4;
	} else {
		if (yych <= 'T') goto yy295;
		if (yych <= 'U') goto yy296;
		goto yy4;
	}
yy249:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy297;
	goto yy4;
yy250:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy298;
	goto yy4;
yy251:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy299;
	goto yy4;
yy252:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy300;
	if (yych == 'I') goto yy301;
	goto yy4;
yy253:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy302;
	if (yych == 'T') goto yy303;
	goto yy4;
yy254:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy304;
	goto yy4;
yy255:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy305;
	goto yy4;
yy256:
	yych = (unsigned char)*++cur;
	switch (yych) {
	case 'E':	goto yy306;
	case 'H':	goto yy307;
	case 'K':	goto yy308;
	case 'T':	goto yy309;
	default:	goto yy4;
	}
yy257:
	yych = (unsigned char)*++cur;
	if (yych == 'v') goto yy310;
	goto yy4;
yy258:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy311;
	goto yy4;
yy259:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy312;
	goto yy4;
yy260:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy313;
	goto yy4;
yy261:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy314;
	goto yy4;
yy262:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy315;
	goto yy4;
yy263:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy316;
	goto yy4;
yy264:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy318;
	goto yy4;
yy265:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy319;
	goto yy4;
yy266:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy320;
	goto yy4;
yy267:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy321;
	goto yy4;
yy268:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy322;
	goto yy4;
yy269:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy323;
	goto yy4;
yy270:
	yych = (unsigned char)*++cur;
	if (yych == '1') goto yy324;
	if (yych == '8') goto yy107;
	goto yy4;
yy271:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy325;
	goto yy4;
yy272:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy326;
	goto yy4;
yy273:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 152 "../src/parse/lex_conf.re"
	{
        const int32_t n = lex_conf_number ();
        if (n < 0) {
            msg.error(cur_loc(), "configuration 'indent:top' must be nonnegative");
            exit(1);
        }
        opts.set_topIndent (static_cast<uint32_t> (n));
        return;
    }
#line 1455 "src/parse/lex_conf.cc"
yy275:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy327;
	goto yy4;
yy276:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy328;
	goto yy4;
yy277:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy329;
	goto yy4;
yy278:
	yyaccept = 1;
	yych = (unsigned char)*(mar = ++cur);
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	if (yych <= 0x1F) {
		if (yych == '\t') {
			ctx = cur;
			goto yy331;
		}
	} else {
		if (yych <= ' ') {
			ctx = cur;
			goto yy331;
		}
		if (yych == '=') {
			ctx = cur;
			goto yy333;
		}
	}
yy279:
#line 180 "../src/parse/lex_conf.re"
	{ opts.set_startlabel       (lex_conf_string()); return; }
#line 1492 "src/parse/lex_conf.cc"
yy280:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy335;
	goto yy4;
yy281:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy337;
	goto yy4;
yy282:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy338;
	goto yy4;
yy283:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy339;
	goto yy4;
yy284:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy341;
	goto yy4;
yy285:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy342;
	goto yy4;
yy286:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy343;
	goto yy4;
yy287:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy344;
	goto yy4;
yy288:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy345;
	goto yy4;
yy289:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy346;
	goto yy4;
yy290:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy347;
	goto yy4;
yy291:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy349;
	goto yy243;
yy292:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy350;
	goto yy4;
yy293:
	yych = (unsigned char)*++cur;
	if (yych == 'C') goto yy351;
	goto yy4;
yy294:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy352;
	goto yy4;
yy295:
	yych = (unsigned char)*++cur;
	if (yych <= 'W') goto yy4;
	if (yych <= 'X') goto yy353;
	if (yych <= 'Y') goto yy354;
	goto yy4;
yy296:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy355;
	goto yy4;
yy297:
	yych = (unsigned char)*++cur;
	if (yych == 'B') goto yy356;
	goto yy4;
yy298:
	yych = (unsigned char)*++cur;
	if (yych == 'L') goto yy357;
	goto yy4;
yy299:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy358;
	goto yy4;
yy300:
	yych = (unsigned char)*++cur;
	if (yych == 'S') goto yy359;
	goto yy4;
yy301:
	yych = (unsigned char)*++cur;
	if (yych == 'M') goto yy360;
	goto yy4;
yy302:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy361;
	goto yy4;
yy303:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy362;
	goto yy4;
yy304:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy363;
	goto yy4;
yy305:
	yych = (unsigned char)*++cur;
	if (yych == 'S') goto yy364;
	goto yy4;
yy306:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy365;
	goto yy4;
yy307:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy366;
	goto yy4;
yy308:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy367;
	goto yy4;
yy309:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy368;
	goto yy4;
yy310:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy369;
	goto yy4;
yy311:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy370;
	if (yych == 'r') goto yy371;
	goto yy4;
yy312:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy372;
	goto yy4;
yy313:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy373;
	goto yy4;
yy314:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy374;
	goto yy4;
yy315:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy375;
	goto yy4;
yy316:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 78 "../src/parse/lex_conf.re"
	{ lex_conf_input(opts);            return; }
#line 1647 "src/parse/lex_conf.cc"
yy318:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy376;
	goto yy4;
yy319:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy377;
	goto yy4;
yy320:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy378;
	goto yy4;
yy321:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy379;
	goto yy4;
yy322:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy380;
	goto yy4;
yy323:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy381;
	goto yy4;
yy324:
	yych = (unsigned char)*++cur;
	if (yych == '6') goto yy135;
	goto yy4;
yy325:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy382;
	goto yy4;
yy326:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy383;
	goto yy4;
yy327:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy384;
	goto yy4;
yy328:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy385;
	goto yy4;
yy329:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 176 "../src/parse/lex_conf.re"
	{ opts.set_labelPrefix (lex_conf_string ()); return; }
#line 1699 "src/parse/lex_conf.cc"
yy331:
	++cur;
	if (lim <= cur) YYFILL(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 64) {
		goto yy331;
	}
	if (yych != '=') goto yy243;
yy333:
	++cur;
	if ((lim - cur) < 2) YYFILL(2);
	yych = (unsigned char)*cur;
	if (yych <= ',') {
		if (yych <= '\t') {
			if (yych <= 0x08) goto yy243;
			goto yy333;
		} else {
			if (yych == ' ') goto yy333;
			goto yy243;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '-') goto yy387;
			goto yy243;
		} else {
			if (yych <= '0') goto yy388;
			if (yych <= '9') goto yy390;
			goto yy243;
		}
	}
yy335:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 107 "../src/parse/lex_conf.re"
	{ opts.set_bUseStateAbort  (lex_conf_bool()); return; }
#line 1737 "src/parse/lex_conf.cc"
yy337:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy392;
	goto yy4;
yy338:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy393;
	goto yy4;
yy339:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 148 "../src/parse/lex_conf.re"
	{ opts.set_tags_prefix    (lex_conf_string ()); return; }
#line 1753 "src/parse/lex_conf.cc"
yy341:
	yych = (unsigned char)*++cur;
	if (yych <= 'c') {
		if (yych <= '`') goto yy4;
		if (yych <= 'a') goto yy394;
		if (yych <= 'b') goto yy395;
		goto yy396;
	} else {
		if (yych <= 'r') goto yy4;
		if (yych <= 's') goto yy397;
		if (yych <= 't') goto yy398;
		goto yy4;
	}
yy342:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy399;
	goto yy4;
yy343:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy400;
	goto yy4;
yy344:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy402;
	goto yy4;
yy345:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy403;
	goto yy4;
yy346:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy404;
	goto yy4;
yy347:
	yyaccept = 2;
	yych = (unsigned char)*(mar = ++cur);
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	if (yych == '@') goto yy405;
yy348:
#line 94 "../src/parse/lex_conf.re"
	{ opts.set_condDivider      (lex_conf_string ()); return; }
#line 1797 "src/parse/lex_conf.cc"
yy349:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy406;
	goto yy243;
yy350:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy407;
	goto yy4;
yy351:
	yych = (unsigned char)*++cur;
	if (yych == 'K') goto yy408;
	goto yy4;
yy352:
	yych = (unsigned char)*++cur;
	if (yych == 'D') goto yy409;
	goto yy4;
yy353:
	yych = (unsigned char)*++cur;
	if (yych == 'M') goto yy410;
	goto yy4;
yy354:
	yych = (unsigned char)*++cur;
	if (yych == 'P') goto yy411;
	goto yy4;
yy355:
	yych = (unsigned char)*++cur;
	if (yych == 'S') goto yy412;
	goto yy4;
yy356:
	yych = (unsigned char)*++cur;
	if (yych == 'U') goto yy413;
	goto yy4;
yy357:
	yych = (unsigned char)*++cur;
	if (yych == 'L') goto yy414;
	goto yy4;
yy358:
	yych = (unsigned char)*++cur;
	if (yych == 'C') goto yy416;
	if (yych == 'S') goto yy417;
	goto yy4;
yy359:
	yych = (unsigned char)*++cur;
	if (yych == 'S') goto yy418;
	goto yy4;
yy360:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy419;
	goto yy4;
yy361:
	yych = (unsigned char)*++cur;
	if (yych == 'K') goto yy420;
	goto yy4;
yy362:
	yych = (unsigned char)*++cur;
	if (yych == 'G') goto yy421;
	goto yy4;
yy363:
	yych = (unsigned char)*++cur;
	if (yych == 'K') goto yy422;
	goto yy4;
yy364:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy424;
	goto yy4;
yy365:
	yych = (unsigned char)*++cur;
	if (yych == 'C') goto yy425;
	if (yych == 'S') goto yy426;
	goto yy4;
yy366:
	yych = (unsigned char)*++cur;
	if (yych == 'F') goto yy427;
	goto yy4;
yy367:
	yych = (unsigned char)*++cur;
	if (yych == 'P') goto yy428;
	goto yy4;
yy368:
	yych = (unsigned char)*++cur;
	if (yych == 'G') goto yy430;
	goto yy4;
yy369:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy431;
	goto yy4;
yy370:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy432;
	goto yy4;
yy371:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy433;
	goto yy4;
yy372:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy434;
	goto yy4;
yy373:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy435;
	goto yy4;
yy374:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy436;
	goto yy4;
yy375:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy437;
	goto yy4;
yy376:
	yych = (unsigned char)*++cur;
	if (yych == 'w') goto yy438;
	goto yy4;
yy377:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy439;
	goto yy4;
yy378:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy440;
	goto yy4;
yy379:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy441;
	goto yy4;
yy380:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy442;
	goto yy4;
yy381:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy443;
	goto yy4;
yy382:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy444;
	goto yy4;
yy383:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy445;
	goto yy4;
yy384:
	yych = (unsigned char)*++cur;
	if (yych == 'L') goto yy447;
	goto yy4;
yy385:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 106 "../src/parse/lex_conf.re"
	{ opts.set_yynext          (lex_conf_string ()); return; }
#line 1951 "src/parse/lex_conf.cc"
yy387:
	yych = (unsigned char)*++cur;
	if (yych <= '0') goto yy243;
	if (yych <= '9') goto yy390;
	goto yy243;
yy388:
	++cur;
yy389:
	cur = ctx;
#line 179 "../src/parse/lex_conf.re"
	{ opts.set_startlabel_force (lex_conf_bool());   return; }
#line 1963 "src/parse/lex_conf.cc"
yy390:
	++cur;
	if (lim <= cur) YYFILL(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 128) {
		goto yy390;
	}
	goto yy389;
yy392:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy448;
	goto yy4;
yy393:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy449;
	goto yy4;
yy394:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy450;
	goto yy4;
yy395:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy451;
	goto yy4;
yy396:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy453;
	if (yych == 't') goto yy455;
	goto yy4;
yy397:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy456;
	goto yy4;
yy398:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy457;
	goto yy4;
yy399:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy458;
	goto yy4;
yy400:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 174 "../src/parse/lex_conf.re"
	{ opts.set_fill_check   (lex_conf_bool()); return; }
#line 2012 "src/parse/lex_conf.cc"
yy402:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy459;
	goto yy4;
yy403:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy461;
	goto yy4;
yy404:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy462;
	goto yy4;
yy405:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy463;
	goto yy243;
yy406:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy464;
	goto yy243;
yy407:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy466;
	goto yy4;
yy408:
	yych = (unsigned char)*++cur;
	if (yych == 'U') goto yy468;
	goto yy4;
yy409:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy469;
	goto yy4;
yy410:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy470;
	goto yy4;
yy411:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy471;
	goto yy4;
yy412:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy473;
	goto yy4;
yy413:
	yych = (unsigned char)*++cur;
	if (yych == 'G') goto yy474;
	goto yy4;
yy414:
	yyaccept = 3;
	yych = (unsigned char)*(mar = ++cur);
	if (yych <= '?') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= '9') goto yy3;
			if (yych <= ':') goto yy476;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy477;
			if (yych <= 'Z') goto yy3;
		} else {
			if (yych == '`') goto yy415;
			if (yych <= 'z') goto yy3;
		}
	}
yy415:
#line 169 "../src/parse/lex_conf.re"
	{ opts.set_fill         (lex_conf_string ()); return; }
#line 2083 "src/parse/lex_conf.cc"
yy416:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy478;
	goto yy4;
yy417:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy479;
	goto yy4;
yy418:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy480;
	goto yy4;
yy419:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy481;
	goto yy4;
yy420:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy483;
	goto yy4;
yy421:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy484;
	if (yych == 'P') goto yy486;
	goto yy4;
yy422:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 129 "../src/parse/lex_conf.re"
	{ opts.set_yypeek       (lex_conf_string ()); return; }
#line 2116 "src/parse/lex_conf.cc"
yy424:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy488;
	goto yy4;
yy425:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy489;
	goto yy4;
yy426:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy490;
	goto yy4;
yy427:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy491;
	goto yy4;
yy428:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 130 "../src/parse/lex_conf.re"
	{ opts.set_yyskip       (lex_conf_string ()); return; }
#line 2140 "src/parse/lex_conf.cc"
yy430:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy493;
	if (yych == 'P') goto yy495;
	goto yy4;
yy431:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy497;
	goto yy4;
yy432:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy498;
	if (yych == 'v') goto yy499;
	goto yy4;
yy433:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy500;
	goto yy4;
yy434:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy501;
	goto yy4;
yy435:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy502;
	goto yy4;
yy436:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy503;
	goto yy4;
yy437:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy504;
	goto yy4;
yy438:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy505;
	goto yy4;
yy439:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy506;
	goto yy4;
yy440:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy507;
	goto yy4;
yy441:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy508;
	goto yy4;
yy442:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy509;
	goto yy4;
yy443:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	goto yy132;
yy444:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy510;
	goto yy4;
yy445:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 151 "../src/parse/lex_conf.re"
	{ opts.set_indString (lex_conf_string ()); return; }
#line 2212 "src/parse/lex_conf.cc"
yy447:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy511;
	goto yy4;
yy448:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy512;
	goto yy4;
yy449:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy513;
	goto yy4;
yy450:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy514;
	goto yy4;
yy451:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 111 "../src/parse/lex_conf.re"
	{ opts.set_yybm         (lex_conf_string ()); return; }
#line 2236 "src/parse/lex_conf.cc"
yy453:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 165 "../src/parse/lex_conf.re"
	{ opts.set_yych           (lex_conf_string ()); return; }
#line 2244 "src/parse/lex_conf.cc"
yy455:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy515;
	goto yy4;
yy456:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy516;
	goto yy4;
yy457:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy517;
	goto yy4;
yy458:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy518;
	goto yy4;
yy459:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 170 "../src/parse/lex_conf.re"
	{ opts.set_fill_use     (lex_conf_bool()); return; }
#line 2268 "src/parse/lex_conf.cc"
yy461:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy519;
	goto yy4;
yy462:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy520;
	goto yy4;
yy463:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy522;
	goto yy243;
yy464:
	++cur;
#line 97 "../src/parse/lex_conf.re"
	{ opts.set_condGotoParam    (lex_conf_string ()); return; }
#line 2285 "src/parse/lex_conf.cc"
yy466:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 93 "../src/parse/lex_conf.re"
	{ opts.set_condEnumPrefix   (lex_conf_string ()); return; }
#line 2293 "src/parse/lex_conf.cc"
yy468:
	yych = (unsigned char)*++cur;
	if (yych == 'P') goto yy523;
	goto yy4;
yy469:
	yych = (unsigned char)*++cur;
	if (yych == 'Y') goto yy525;
	goto yy4;
yy470:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy526;
	goto yy4;
yy471:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 164 "../src/parse/lex_conf.re"
	{ opts.set_yyctype        (lex_conf_string ()); return; }
#line 2313 "src/parse/lex_conf.cc"
yy473:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy527;
	goto yy4;
yy474:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 162 "../src/parse/lex_conf.re"
	{ opts.set_yydebug (lex_conf_string ()); return; }
#line 2325 "src/parse/lex_conf.cc"
yy476:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy529;
	goto yy4;
yy477:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy530;
	goto yy243;
yy478:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy531;
	goto yy4;
yy479:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy532;
	goto yy4;
yy480:
	yych = (unsigned char)*++cur;
	if (yych == 'H') goto yy533;
	goto yy4;
yy481:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 127 "../src/parse/lex_conf.re"
	{ opts.set_yylimit     (lex_conf_string ()); return; }
#line 2353 "src/parse/lex_conf.cc"
yy483:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy534;
	goto yy4;
yy484:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 139 "../src/parse/lex_conf.re"
	{ opts.set_yymtagn      (lex_conf_string ()); return; }
#line 2365 "src/parse/lex_conf.cc"
yy486:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 140 "../src/parse/lex_conf.re"
	{ opts.set_yymtagp      (lex_conf_string ()); return; }
#line 2373 "src/parse/lex_conf.cc"
yy488:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy536;
	goto yy4;
yy489:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy537;
	goto yy4;
yy490:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy538;
	goto yy4;
yy491:
	yych = (unsigned char)*++cur;
	if (yych <= 'M') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= ':') goto yy3;
			if (yych <= '@') goto yy492;
			if (yych <= 'L') goto yy3;
			goto yy539;
		}
	} else {
		if (yych <= '^') {
			if (yych == 'S') goto yy540;
			if (yych <= 'Z') goto yy3;
		} else {
			if (yych == '`') goto yy492;
			if (yych <= 'z') goto yy3;
		}
	}
yy492:
#line 141 "../src/parse/lex_conf.re"
	{ opts.set_yyshift      (lex_conf_string ()); return; }
#line 2409 "src/parse/lex_conf.cc"
yy493:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 137 "../src/parse/lex_conf.re"
	{ opts.set_yystagn      (lex_conf_string ()); return; }
#line 2417 "src/parse/lex_conf.cc"
yy495:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 138 "../src/parse/lex_conf.re"
	{ opts.set_yystagp      (lex_conf_string ()); return; }
#line 2425 "src/parse/lex_conf.cc"
yy497:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy541;
	goto yy4;
yy498:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy542;
	goto yy4;
yy499:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy543;
	goto yy4;
yy500:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy544;
	goto yy4;
yy501:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy545;
	goto yy4;
yy502:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy546;
	goto yy4;
yy503:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy547;
	goto yy4;
yy504:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy548;
	goto yy4;
yy505:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy549;
	goto yy4;
yy506:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy550;
	goto yy4;
yy507:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy551;
	goto yy4;
yy508:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy552;
	goto yy4;
yy509:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy553;
	goto yy4;
yy510:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy554;
	goto yy4;
yy511:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy555;
	goto yy4;
yy512:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy556;
	goto yy4;
yy513:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy558;
	goto yy4;
yy514:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy560;
	goto yy4;
yy515:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy561;
	goto yy4;
yy516:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy562;
	goto yy4;
yy517:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy563;
	goto yy4;
yy518:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy564;
	goto yy4;
yy519:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy566;
	goto yy4;
yy520:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 113 "../src/parse/lex_conf.re"
	{
        const int32_t n = lex_conf_number ();
        if (n < 0) {
            msg.error(cur_loc(), "configuration 'cgoto:threshold' must be nonnegative");
            exit(1);
        }
        opts.set_cGotoThreshold (static_cast<uint32_t> (n));
        return;
    }
#line 2533 "src/parse/lex_conf.cc"
yy522:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy567;
	goto yy243;
yy523:
	yych = (unsigned char)*++cur;
	if (yych <= 'B') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= ':') goto yy3;
			if (yych >= 'A') goto yy3;
		}
	} else {
		if (yych <= '^') {
			if (yych <= 'C') goto yy568;
			if (yych <= 'Z') goto yy3;
		} else {
			if (yych == '`') goto yy524;
			if (yych <= 'z') goto yy3;
		}
	}
yy524:
#line 131 "../src/parse/lex_conf.re"
	{ opts.set_yybackup     (lex_conf_string ()); return; }
#line 2559 "src/parse/lex_conf.cc"
yy525:
	yych = (unsigned char)*++cur;
	if (yych == 'P') goto yy569;
	goto yy4;
yy526:
	yych = (unsigned char)*++cur;
	if (yych == 'K') goto yy570;
	goto yy4;
yy527:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 124 "../src/parse/lex_conf.re"
	{ opts.set_yycursor    (lex_conf_string ()); return; }
#line 2575 "src/parse/lex_conf.cc"
yy529:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy571;
	goto yy4;
yy530:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy572;
	goto yy243;
yy531:
	yych = (unsigned char)*++cur;
	if (yych == 'D') goto yy573;
	goto yy4;
yy532:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy574;
	goto yy4;
yy533:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy575;
	goto yy4;
yy534:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 125 "../src/parse/lex_conf.re"
	{ opts.set_yymarker    (lex_conf_string ()); return; }
#line 2603 "src/parse/lex_conf.cc"
yy536:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy576;
	goto yy4;
yy537:
	yych = (unsigned char)*++cur;
	if (yych == 'D') goto yy578;
	goto yy4;
yy538:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy579;
	goto yy4;
yy539:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy580;
	goto yy4;
yy540:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy581;
	goto yy4;
yy541:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy582;
	goto yy4;
yy542:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy583;
	goto yy4;
yy543:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy584;
	goto yy4;
yy544:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy585;
	goto yy4;
yy545:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy586;
	goto yy4;
yy546:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy587;
	goto yy4;
yy547:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy588;
	goto yy4;
yy548:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy589;
	goto yy4;
yy549:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy590;
	goto yy4;
yy550:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy127;
	goto yy4;
yy551:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy591;
	goto yy4;
yy552:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy592;
	goto yy4;
yy553:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy593;
	goto yy4;
yy554:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy594;
	goto yy4;
yy555:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy595;
	goto yy4;
yy556:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 108 "../src/parse/lex_conf.re"
	{ opts.set_bUseStateNext   (lex_conf_bool()); return; }
#line 2691 "src/parse/lex_conf.cc"
yy558:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 149 "../src/parse/lex_conf.re"
	{ opts.set_tags_expression(lex_conf_string ()); return; }
#line 2699 "src/parse/lex_conf.cc"
yy560:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy596;
	goto yy4;
yy561:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy597;
	goto yy4;
yy562:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy598;
	goto yy4;
yy563:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy599;
	goto yy4;
yy564:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 166 "../src/parse/lex_conf.re"
	{ opts.set_yychConversion (lex_conf_bool()); return; }
#line 2723 "src/parse/lex_conf.cc"
yy566:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy600;
	goto yy4;
yy567:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy602;
	goto yy243;
yy568:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy604;
	goto yy4;
yy569:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy605;
	goto yy4;
yy570:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy607;
	goto yy4;
yy571:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy608;
	goto yy4;
yy572:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy609;
	goto yy243;
yy573:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy611;
	goto yy4;
yy574:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy612;
	goto yy4;
yy575:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy614;
	goto yy4;
yy576:
	yych = (unsigned char)*++cur;
	if (yych <= 'C') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= ':') goto yy3;
			if (yych <= '@') goto yy577;
			if (yych <= 'B') goto yy3;
			goto yy616;
		}
	} else {
		if (yych <= '^') {
			if (yych == 'T') goto yy617;
			if (yych <= 'Z') goto yy3;
		} else {
			if (yych == '`') goto yy577;
			if (yych <= 'z') goto yy3;
		}
	}
yy577:
#line 133 "../src/parse/lex_conf.re"
	{ opts.set_yyrestore    (lex_conf_string ()); return; }
#line 2787 "src/parse/lex_conf.cc"
yy578:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy618;
	goto yy4;
yy579:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy619;
	goto yy4;
yy580:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy621;
	goto yy4;
yy581:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy622;
	goto yy4;
yy582:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy623;
	goto yy4;
yy583:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy624;
	goto yy4;
yy584:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy625;
	goto yy4;
yy585:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy626;
	goto yy4;
yy586:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy628;
	goto yy4;
yy587:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy629;
	goto yy4;
yy588:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy630;
	goto yy4;
yy589:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy632;
	goto yy4;
yy590:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy633;
	goto yy4;
yy591:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy635;
	goto yy4;
yy592:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy636;
	goto yy4;
yy593:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy637;
	goto yy4;
yy594:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	goto yy134;
yy595:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy638;
	goto yy4;
yy596:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy640;
	goto yy4;
yy597:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy642;
	goto yy4;
yy598:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy644;
	goto yy4;
yy599:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy646;
	goto yy4;
yy600:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 172 "../src/parse/lex_conf.re"
	{ opts.set_fill_arg_use (lex_conf_bool()); return; }
#line 2885 "src/parse/lex_conf.cc"
yy602:
	++cur;
#line 95 "../src/parse/lex_conf.re"
	{ opts.set_condDividerParam (lex_conf_string ()); return; }
#line 2890 "src/parse/lex_conf.cc"
yy604:
	yych = (unsigned char)*++cur;
	if (yych == 'X') goto yy648;
	goto yy4;
yy605:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 86 "../src/parse/lex_conf.re"
	{ opts.set_yycondtype       (lex_conf_string ()); return; }
#line 2902 "src/parse/lex_conf.cc"
yy607:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy650;
	goto yy4;
yy608:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy652;
	goto yy4;
yy609:
	++cur;
#line 171 "../src/parse/lex_conf.re"
	{ opts.set_fill_arg     (lex_conf_string ()); return; }
#line 2915 "src/parse/lex_conf.cc"
yy611:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy653;
	goto yy4;
yy612:
	yych = (unsigned char)*++cur;
	if (yych <= '@') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= '9') goto yy3;
			if (yych <= ':') goto yy654;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy3;
			if (yych >= '_') goto yy3;
		} else {
			if (yych <= '`') goto yy613;
			if (yych <= 'z') goto yy3;
		}
	}
yy613:
#line 100 "../src/parse/lex_conf.re"
	{ opts.set_state_get       (lex_conf_string ()); return; }
#line 2941 "src/parse/lex_conf.cc"
yy614:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 136 "../src/parse/lex_conf.re"
	{ opts.set_yylessthan   (lex_conf_string ()); return; }
#line 2949 "src/parse/lex_conf.cc"
yy616:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy655;
	goto yy4;
yy617:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy656;
	goto yy4;
yy618:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy657;
	goto yy4;
yy619:
	yyaccept = 4;
	yych = (unsigned char)*(mar = ++cur);
	if (yych <= '?') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= '9') goto yy3;
			if (yych <= ':') goto yy658;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy659;
			if (yych <= 'Z') goto yy3;
		} else {
			if (yych == '`') goto yy620;
			if (yych <= 'z') goto yy3;
		}
	}
yy620:
#line 102 "../src/parse/lex_conf.re"
	{ opts.set_state_set       (lex_conf_string ()); return; }
#line 2984 "src/parse/lex_conf.cc"
yy621:
	yych = (unsigned char)*++cur;
	if (yych == 'G') goto yy660;
	goto yy4;
yy622:
	yych = (unsigned char)*++cur;
	if (yych == 'G') goto yy662;
	goto yy4;
yy623:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	goto yy114;
yy624:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy664;
	goto yy4;
yy625:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy665;
	goto yy4;
yy626:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 52 "../src/parse/lex_conf.re"
	{ opts.set_case_ranges      (lex_conf_bool());   return; }
#line 3014 "src/parse/lex_conf.cc"
yy628:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy666;
	goto yy4;
yy629:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy667;
	goto yy4;
yy630:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 79 "../src/parse/lex_conf.re"
	{ lex_conf_empty_class(opts);      return; }
#line 3030 "src/parse/lex_conf.cc"
yy632:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy668;
	goto yy4;
yy633:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 53 "../src/parse/lex_conf.re"
	{ opts.set_loop_switch      (lex_conf_bool());   return; }
#line 3042 "src/parse/lex_conf.cc"
yy635:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy669;
	goto yy4;
yy636:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy670;
	goto yy4;
yy637:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	goto yy130;
yy638:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 105 "../src/parse/lex_conf.re"
	{ opts.set_yyfilllabel     (lex_conf_string ()); return; }
#line 3064 "src/parse/lex_conf.cc"
yy640:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 109 "../src/parse/lex_conf.re"
	{ opts.set_yyaccept        (lex_conf_string ()); return; }
#line 3072 "src/parse/lex_conf.cc"
yy642:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 98 "../src/parse/lex_conf.re"
	{ opts.set_yyctable         (lex_conf_string ()); return; }
#line 3080 "src/parse/lex_conf.cc"
yy644:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 183 "../src/parse/lex_conf.re"
	{ lex_conf_string (); return; }
#line 3088 "src/parse/lex_conf.cc"
yy646:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 122 "../src/parse/lex_conf.re"
	{ opts.set_yytarget (lex_conf_string ()); return; }
#line 3096 "src/parse/lex_conf.cc"
yy648:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 132 "../src/parse/lex_conf.re"
	{ opts.set_yybackupctx  (lex_conf_string ()); return; }
#line 3104 "src/parse/lex_conf.cc"
yy650:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 126 "../src/parse/lex_conf.re"
	{ opts.set_yyctxmarker (lex_conf_string ()); return; }
#line 3112 "src/parse/lex_conf.cc"
yy652:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy671;
	goto yy4;
yy653:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy673;
	goto yy4;
yy654:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy674;
	goto yy4;
yy655:
	yych = (unsigned char)*++cur;
	if (yych == 'X') goto yy675;
	goto yy4;
yy656:
	yych = (unsigned char)*++cur;
	if (yych == 'G') goto yy677;
	goto yy4;
yy657:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy679;
	goto yy4;
yy658:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy680;
	goto yy4;
yy659:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy681;
	goto yy243;
yy660:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 143 "../src/parse/lex_conf.re"
	{ opts.set_yyshiftmtag  (lex_conf_string ()); return; }
#line 3152 "src/parse/lex_conf.cc"
yy662:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 142 "../src/parse/lex_conf.re"
	{ opts.set_yyshiftstag  (lex_conf_string ()); return; }
#line 3160 "src/parse/lex_conf.cc"
yy664:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy682;
	goto yy4;
yy665:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy683;
	goto yy4;
yy666:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy685;
	goto yy4;
yy667:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	goto yy117;
yy668:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy686;
	goto yy4;
yy669:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy687;
	goto yy4;
yy670:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy688;
	goto yy4;
yy671:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 173 "../src/parse/lex_conf.re"
	{ opts.set_fill_naked   (lex_conf_bool()); return; }
#line 3198 "src/parse/lex_conf.cc"
yy673:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy689;
	goto yy4;
yy674:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy690;
	goto yy4;
yy675:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 134 "../src/parse/lex_conf.re"
	{ opts.set_yyrestorectx (lex_conf_string ()); return; }
#line 3214 "src/parse/lex_conf.cc"
yy677:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 135 "../src/parse/lex_conf.re"
	{ opts.set_yyrestoretag (lex_conf_string ()); return; }
#line 3222 "src/parse/lex_conf.cc"
yy679:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy691;
	goto yy4;
yy680:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy692;
	goto yy4;
yy681:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy693;
	goto yy243;
yy682:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy694;
	goto yy4;
yy683:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 51 "../src/parse/lex_conf.re"
	{ opts.set_bCaseInverted    (lex_conf_bool());   return; }
#line 3246 "src/parse/lex_conf.cc"
yy685:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy120;
	goto yy4;
yy686:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy695;
	goto yy4;
yy687:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
	goto yy123;
yy688:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy109;
	goto yy4;
yy689:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy696;
	goto yy4;
yy690:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy698;
	goto yy4;
yy691:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy699;
	goto yy4;
yy692:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy701;
	goto yy4;
yy693:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy702;
	goto yy243;
yy694:
	yych = (unsigned char)*++cur;
	if (yych == 'v') goto yy703;
	goto yy4;
yy695:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy704;
	goto yy4;
yy696:
	yych = (unsigned char)*++cur;
	if (yych <= '@') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= '9') goto yy3;
			if (yych <= ':') goto yy706;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy3;
			if (yych >= '_') goto yy3;
		} else {
			if (yych <= '`') goto yy697;
			if (yych <= 'z') goto yy3;
		}
	}
yy697:
#line 87 "../src/parse/lex_conf.re"
	{ opts.set_cond_get         (lex_conf_string ()); return; }
#line 3314 "src/parse/lex_conf.cc"
yy698:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy707;
	goto yy4;
yy699:
	yyaccept = 5;
	yych = (unsigned char)*(mar = ++cur);
	if (yych <= '?') {
		if (yych <= '/') {
			if (yych == '-') goto yy3;
		} else {
			if (yych <= '9') goto yy3;
			if (yych <= ':') goto yy708;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy709;
			if (yych <= 'Z') goto yy3;
		} else {
			if (yych == '`') goto yy700;
			if (yych <= 'z') goto yy3;
		}
	}
yy700:
#line 89 "../src/parse/lex_conf.re"
	{ opts.set_cond_set         (lex_conf_string ()); return; }
#line 3341 "src/parse/lex_conf.cc"
yy701:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy710;
	goto yy4;
yy702:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy711;
	goto yy243;
yy703:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy712;
	goto yy4;
yy704:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 77 "../src/parse/lex_conf.re"
	{ lex_conf_encoding_policy(opts);  return; }
#line 3361 "src/parse/lex_conf.cc"
yy706:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy714;
	goto yy4;
yy707:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy715;
	goto yy4;
yy708:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy717;
	goto yy4;
yy709:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy718;
	goto yy243;
yy710:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy719;
	goto yy4;
yy711:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy721;
	goto yy243;
yy712:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 50 "../src/parse/lex_conf.re"
	{ opts.set_bCaseInsensitive (lex_conf_bool());   return; }
#line 3393 "src/parse/lex_conf.cc"
yy714:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy723;
	goto yy4;
yy715:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 101 "../src/parse/lex_conf.re"
	{ opts.set_state_get_naked (lex_conf_bool()); return; }
#line 3405 "src/parse/lex_conf.cc"
yy717:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy724;
	goto yy4;
yy718:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy725;
	goto yy243;
yy719:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 103 "../src/parse/lex_conf.re"
	{ opts.set_state_set_naked (lex_conf_bool()); return; }
#line 3421 "src/parse/lex_conf.cc"
yy721:
	++cur;
#line 104 "../src/parse/lex_conf.re"
	{ opts.set_state_set_arg   (lex_conf_string ()); return; }
#line 3426 "src/parse/lex_conf.cc"
yy723:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy726;
	goto yy4;
yy724:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy727;
	goto yy4;
yy725:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy728;
	goto yy243;
yy726:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy729;
	goto yy4;
yy727:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy730;
	goto yy4;
yy728:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy731;
	goto yy243;
yy729:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy733;
	goto yy4;
yy730:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy735;
	goto yy4;
yy731:
	++cur;
#line 90 "../src/parse/lex_conf.re"
	{ opts.set_cond_set_arg     (lex_conf_string ()); return; }
#line 3463 "src/parse/lex_conf.cc"
yy733:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 88 "../src/parse/lex_conf.re"
	{ opts.set_cond_get_naked   (lex_conf_bool()); return; }
#line 3471 "src/parse/lex_conf.cc"
yy735:
	yych = (unsigned char)*++cur;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 91 "../src/parse/lex_conf.re"
	{ opts.set_cond_set_naked   (lex_conf_bool()); return; }
#line 3479 "src/parse/lex_conf.cc"
}
#line 197 "../src/parse/lex_conf.re"

}

void Scanner::lex_conf_encoding_policy(Opt &opts)
{
    lex_conf_assign ();

#line 3489 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	if ((lim - cur) < 10) YYFILL(10);
	yych = (unsigned char)*cur;
	if (yych <= 'h') {
		if (yych == 'f') goto yy741;
	} else {
		if (yych <= 'i') goto yy742;
		if (yych == 's') goto yy743;
	}
	++cur;
yy740:
#line 204 "../src/parse/lex_conf.re"
	{
        msg.error(cur_loc(),
            "bad configuration value (expected: 'ignore', 'substitute', 'fail')");
        exit(1);
    }
#line 3508 "src/parse/lex_conf.cc"
yy741:
	yych = (unsigned char)*(mar = ++cur);
	if (yych == 'a') goto yy744;
	goto yy740;
yy742:
	yych = (unsigned char)*(mar = ++cur);
	if (yych == 'g') goto yy746;
	goto yy740;
yy743:
	yych = (unsigned char)*(mar = ++cur);
	if (yych == 'u') goto yy747;
	goto yy740;
yy744:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy748;
yy745:
	cur = mar;
	goto yy740;
yy746:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy749;
	goto yy745;
yy747:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy750;
	goto yy745;
yy748:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy751;
	goto yy745;
yy749:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy753;
	goto yy745;
yy750:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy754;
	goto yy745;
yy751:
	++cur;
#line 211 "../src/parse/lex_conf.re"
	{ opts.set_encoding_policy(Enc::POLICY_FAIL);       goto end; }
#line 3551 "src/parse/lex_conf.cc"
yy753:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy755;
	goto yy745;
yy754:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy756;
	goto yy745;
yy755:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy757;
	goto yy745;
yy756:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy759;
	goto yy745;
yy757:
	++cur;
#line 209 "../src/parse/lex_conf.re"
	{ opts.set_encoding_policy(Enc::POLICY_IGNORE);     goto end; }
#line 3572 "src/parse/lex_conf.cc"
yy759:
	yych = (unsigned char)*++cur;
	if (yych != 't') goto yy745;
	yych = (unsigned char)*++cur;
	if (yych != 'u') goto yy745;
	yych = (unsigned char)*++cur;
	if (yych != 't') goto yy745;
	yych = (unsigned char)*++cur;
	if (yych != 'e') goto yy745;
	++cur;
#line 210 "../src/parse/lex_conf.re"
	{ opts.set_encoding_policy(Enc::POLICY_SUBSTITUTE); goto end; }
#line 3585 "src/parse/lex_conf.cc"
}
#line 212 "../src/parse/lex_conf.re"

end:
    lex_conf_semicolon();
}

void Scanner::lex_conf_input(Opt &opts)
{
    lex_conf_assign ();

#line 3597 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	if ((lim - cur) < 7) YYFILL(7);
	yych = (unsigned char)*cur;
	if (yych <= 'b') goto yy767;
	if (yych <= 'c') goto yy769;
	if (yych <= 'd') goto yy770;
yy767:
	++cur;
yy768:
#line 221 "../src/parse/lex_conf.re"
	{
        msg.error(cur_loc(),
            "bad configuration value (expected: 'default', 'custom')");
        exit(1);
    }
#line 3614 "src/parse/lex_conf.cc"
yy769:
	yych = (unsigned char)*(mar = ++cur);
	if (yych == 'u') goto yy771;
	goto yy768;
yy770:
	yych = (unsigned char)*(mar = ++cur);
	if (yych == 'e') goto yy773;
	goto yy768;
yy771:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy774;
yy772:
	cur = mar;
	goto yy768;
yy773:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy775;
	goto yy772;
yy774:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy776;
	goto yy772;
yy775:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy777;
	goto yy772;
yy776:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy778;
	goto yy772;
yy777:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy779;
	goto yy772;
yy778:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy780;
	goto yy772;
yy779:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy782;
	goto yy772;
yy780:
	++cur;
#line 227 "../src/parse/lex_conf.re"
	{ opts.set_input_api(INPUT_CUSTOM);  goto end; }
#line 3661 "src/parse/lex_conf.cc"
yy782:
	yych = (unsigned char)*++cur;
	if (yych != 't') goto yy772;
	++cur;
#line 226 "../src/parse/lex_conf.re"
	{ opts.set_input_api(INPUT_DEFAULT); goto end; }
#line 3668 "src/parse/lex_conf.cc"
}
#line 228 "../src/parse/lex_conf.re"

end:
    lex_conf_semicolon();
}

void Scanner::lex_conf_empty_class(Opt &opts)
{
    lex_conf_assign ();

#line 3680 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	if ((lim - cur) < 11) YYFILL(11);
	yych = (unsigned char)*cur;
	if (yych == 'e') goto yy789;
	if (yych == 'm') goto yy790;
	++cur;
yy788:
#line 237 "../src/parse/lex_conf.re"
	{
        msg.error(cur_loc(),
            "bad configuration value (expected: 'match-empty', 'match-none', 'error')");
        exit(1);
    }
#line 3695 "src/parse/lex_conf.cc"
yy789:
	yych = (unsigned char)*(mar = ++cur);
	if (yych == 'r') goto yy791;
	goto yy788;
yy790:
	yych = (unsigned char)*(mar = ++cur);
	if (yych == 'a') goto yy793;
	goto yy788;
yy791:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy794;
yy792:
	cur = mar;
	goto yy788;
yy793:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy795;
	goto yy792;
yy794:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy796;
	goto yy792;
yy795:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy797;
	goto yy792;
yy796:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy798;
	goto yy792;
yy797:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy800;
	goto yy792;
yy798:
	++cur;
#line 244 "../src/parse/lex_conf.re"
	{ opts.set_empty_class_policy(EMPTY_CLASS_ERROR);       goto end; }
#line 3734 "src/parse/lex_conf.cc"
yy800:
	yych = (unsigned char)*++cur;
	if (yych != '-') goto yy792;
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy802;
	if (yych == 'n') goto yy803;
	goto yy792;
yy802:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy804;
	goto yy792;
yy803:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy805;
	goto yy792;
yy804:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy806;
	goto yy792;
yy805:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy807;
	goto yy792;
yy806:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy808;
	goto yy792;
yy807:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy809;
	goto yy792;
yy808:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy811;
	goto yy792;
yy809:
	++cur;
#line 243 "../src/parse/lex_conf.re"
	{ opts.set_empty_class_policy(EMPTY_CLASS_MATCH_NONE);  goto end; }
#line 3774 "src/parse/lex_conf.cc"
yy811:
	++cur;
#line 242 "../src/parse/lex_conf.re"
	{ opts.set_empty_class_policy(EMPTY_CLASS_MATCH_EMPTY); goto end; }
#line 3779 "src/parse/lex_conf.cc"
}
#line 245 "../src/parse/lex_conf.re"

end:
    lex_conf_semicolon();
}

void Scanner::lex_conf_api_style(Opt &opts)
{
    lex_conf_assign ();

#line 3791 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	if ((lim - cur) < 9) YYFILL(9);
	yych = (unsigned char)*cur;
	if (yych == 'f') goto yy817;
	++cur;
yy816:
#line 254 "../src/parse/lex_conf.re"
	{
        msg.error(cur_loc(),
            "bad configuration value (expected: 'functions', 'free-form')");
        exit(1);
    }
#line 3805 "src/parse/lex_conf.cc"
yy817:
	yych = (unsigned char)*(mar = ++cur);
	if (yych == 'r') goto yy818;
	if (yych == 'u') goto yy820;
	goto yy816;
yy818:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy821;
yy819:
	cur = mar;
	goto yy816;
yy820:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy822;
	goto yy819;
yy821:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy823;
	goto yy819;
yy822:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy824;
	goto yy819;
yy823:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy825;
	goto yy819;
yy824:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy826;
	goto yy819;
yy825:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy827;
	goto yy819;
yy826:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy828;
	goto yy819;
yy827:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy829;
	goto yy819;
yy828:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy830;
	goto yy819;
yy829:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy831;
	goto yy819;
yy830:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy832;
	goto yy819;
yy831:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy833;
	goto yy819;
yy832:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy835;
	goto yy819;
yy833:
	++cur;
#line 260 "../src/parse/lex_conf.re"
	{ opts.set_api_style(API_FREEFORM);  goto end; }
#line 3873 "src/parse/lex_conf.cc"
yy835:
	++cur;
#line 259 "../src/parse/lex_conf.re"
	{ opts.set_api_style(API_FUNCTIONS); goto end; }
#line 3878 "src/parse/lex_conf.cc"
}
#line 261 "../src/parse/lex_conf.re"

end:
    lex_conf_semicolon();
}

void Scanner::lex_conf_enc(Enc::type_t enc, Opt &opts)
{
    if (lex_conf_bool()) {
        opts.set_encoding(enc);
    } else {
        opts.unset_encoding(enc);
    }
}

void Scanner::lex_conf_assign ()
{

#line 3898 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((lim - cur) < 2) YYFILL(2);
	yych = (unsigned char)*cur;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy841;
	} else {
		if (yych <= ' ') goto yy841;
		if (yych == '=') goto yy842;
	}
	++cur;
yy840:
#line 278 "../src/parse/lex_conf.re"
	{
        msg.error(cur_loc(), "missing '=' in configuration");
        exit(1);
    }
#line 3950 "src/parse/lex_conf.cc"
yy841:
	yych = (unsigned char)*(mar = ++cur);
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy845;
		goto yy840;
	} else {
		if (yych <= ' ') goto yy845;
		if (yych != '=') goto yy840;
	}
yy842:
	++cur;
	if (lim <= cur) YYFILL(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 128) {
		goto yy842;
	}
#line 282 "../src/parse/lex_conf.re"
	{ return; }
#line 3969 "src/parse/lex_conf.cc"
yy845:
	++cur;
	if (lim <= cur) YYFILL(1);
	yych = (unsigned char)*cur;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy845;
	} else {
		if (yych <= ' ') goto yy845;
		if (yych == '=') goto yy842;
	}
	cur = mar;
	goto yy840;
}
#line 283 "../src/parse/lex_conf.re"

}

void Scanner::lex_conf_semicolon ()
{

#line 3990 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((lim - cur) < 2) YYFILL(2);
	yych = (unsigned char)*cur;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy852;
	} else {
		if (yych <= ' ') goto yy852;
		if (yych == ';') goto yy853;
	}
	++cur;
yy851:
#line 289 "../src/parse/lex_conf.re"
	{
        msg.error(cur_loc(), "missing ending ';' in configuration");
        exit(1);
    }
#line 4042 "src/parse/lex_conf.cc"
yy852:
	yych = (unsigned char)*(mar = ++cur);
	if (yybm[0+yych] & 128) {
		goto yy855;
	}
	if (yych != ';') goto yy851;
yy853:
	++cur;
#line 293 "../src/parse/lex_conf.re"
	{ return; }
#line 4053 "src/parse/lex_conf.cc"
yy855:
	++cur;
	if (lim <= cur) YYFILL(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 128) {
		goto yy855;
	}
	if (yych == ';') goto yy853;
	cur = mar;
	goto yy851;
}
#line 294 "../src/parse/lex_conf.re"

}

bool Scanner::lex_conf_bool()
{
    return lex_conf_number() != 0;
}

int32_t Scanner::lex_conf_number ()
{
    lex_conf_assign ();
    tok = cur;

#line 4079 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((lim - cur) < 2) YYFILL(2);
	yych = (unsigned char)*cur;
	if (yych <= '/') {
		if (yych == '-') goto yy862;
	} else {
		if (yych <= '0') goto yy863;
		if (yych <= '9') goto yy865;
	}
	++cur;
yy861:
#line 307 "../src/parse/lex_conf.re"
	{
        msg.error(cur_loc(), "bad configuration value (expected number)");
        exit(1);
    }
#line 4131 "src/parse/lex_conf.cc"
yy862:
	yych = (unsigned char)*++cur;
	if (yych <= '0') goto yy861;
	if (yych <= '9') goto yy865;
	goto yy861;
yy863:
	++cur;
yy864:
#line 311 "../src/parse/lex_conf.re"
	{
        int32_t n = 0;
        if (!s_to_i32_unsafe (tok, cur, n)) {
            msg.error(cur_loc(), "configuration value overflow");
            exit(1);
        }
        lex_conf_semicolon ();
        return n;
    }
#line 4150 "src/parse/lex_conf.cc"
yy865:
	++cur;
	if (lim <= cur) YYFILL(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 128) {
		goto yy865;
	}
	goto yy864;
}
#line 320 "../src/parse/lex_conf.re"

}

uint32_t Scanner::lex_conf_eof()
{
    const int32_t n = lex_conf_number();
    return n < 0 ? NOEOF : static_cast<uint32_t>(n);
}

std::string Scanner::lex_conf_string ()
{
    lex_conf_assign ();
    std::string s;
    tok = cur;

#line 4176 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128,   0,   0, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
	};
	if (lim <= cur) YYFILL(1);
	yych = (unsigned char)*cur;
	if (yych <= '!') {
		if (yych <= '\n') {
			if (yych <= 0x00) goto yy869;
			if (yych <= 0x08) goto yy870;
		} else {
			if (yych != ' ') goto yy870;
		}
	} else {
		if (yych <= '\'') {
			if (yych <= '"') goto yy873;
			if (yych <= '&') goto yy870;
			goto yy873;
		} else {
			if (yych != ';') goto yy870;
		}
	}
yy869:
#line 356 "../src/parse/lex_conf.re"
	{ goto end; }
#line 4234 "src/parse/lex_conf.cc"
yy870:
	++cur;
	if (lim <= cur) YYFILL(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 128) {
		goto yy870;
	}
#line 352 "../src/parse/lex_conf.re"
	{
        s = getstr(tok, cur);
        goto end;
    }
#line 4247 "src/parse/lex_conf.cc"
yy873:
	++cur;
#line 335 "../src/parse/lex_conf.re"
	{
        const char quote = tok[0];
        for (;;) {
            ASTChar c;
            if (!lex_str_chr(quote, c)) {
                goto end;
            }
            if (c.chr > 0xFF) {
                msg.error(c.loc
                    , "multibyte character in configuration string: 0x%X"
                    , c.chr);
                exit(1);
            } else {
                s += static_cast<char>(c.chr);
            }
        }
    }
#line 4268 "src/parse/lex_conf.cc"
}
#line 357 "../src/parse/lex_conf.re"

end:
    lex_conf_semicolon ();
    return s;
}

#undef YYFILL

} // end namespace re2c
